### ISSUE TITLE
Install process

### ISSUE THREAD

**Issue by E-Sh4rk** [AliaumeL/akl#1]
Issue with the config dir creation:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:657:18
`

Issue with the clipboard dependencies:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoBinary', src/main.rs:818:40
`

**Comment by AliaumeL** [comment]
The second issue should be dealt with using 6f1e073733d5369c1e2090d4ede783a0a0d252bd, which uses [x11_fork](https://docs.rs/copypasta-ext/0.4.4/copypasta_ext/x11_fork/index.html) rather  than [x11_bin](https://docs.rs/copypasta-ext/0.4.4/copypasta_ext/x11_bin/index.html) to persist the clipboard after the application terminates.
